# Generated by Django 2.1.15 on 2020-06-17 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DescuentoGeneral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=75)),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=8)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'descuento_general',
            },
        ),
        migrations.CreateModel(
            name='Periodicidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio_periodo', models.IntegerField()),
                ('quincenal', models.BooleanField(default=False)),
                ('mensual', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'periodicidad',
            },
        ),
        migrations.CreateModel(
            name='SalarioMinimo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'salario_minimo',
            },
        ),
    ]
