# Generated by Django 2.1.15 on 2020-06-18 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('descuento_general', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='periodicidad',
            name='quincenal',
        ),
        migrations.AddField(
            model_name='periodicidad',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
