# Generated by Django 2.1.15 on 2020-06-19 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DireccionUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=75)),
                ('url', models.TextField(max_length=75)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.Permission')),
            ],
            options={
                'db_table': 'direccion_url',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=75)),
                ('url', models.TextField(max_length=75)),
                ('group', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='auth.Group')),
                ('sub_menu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='menu', related_query_name='menu', to='usuario.Menu')),
            ],
            options={
                'db_table': 'menu',
            },
        ),
    ]
