# Generated by Django 2.1.15 on 2020-06-20 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=75)),
                ('url', models.TextField(blank=True, max_length=75)),
                ('groups', models.ManyToManyField(blank=True, to='auth.Group')),
                ('padre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='menu', related_query_name='menu', to='usuario.Menu')),
            ],
            options={
                'db_table': 'menu',
            },
        ),
    ]
