# Generated by Django 2.1.15 on 2020-06-19 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('usuario', '0002_direccionurl_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='group',
        ),
        migrations.AddField(
            model_name='menu',
            name='groups',
            field=models.ManyToManyField(blank=True, to='auth.Group'),
        ),
    ]
