# Generated by Django 2.1.15 on 2020-06-24 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='intentos',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
