# Generated by Django 2.1.15 on 2020-06-19 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_auto_20200619_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='url',
            field=models.TextField(blank=True, max_length=75),
        ),
    ]
