# Generated by Django 2.1.15 on 2020-06-17 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoletaPago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.TextField(max_length=20)),
                ('fecha_pago', models.DateField()),
                ('dias_laborales', models.IntegerField(default=23)),
                ('dias_trabajados', models.IntegerField(default=23)),
                ('salario_actual', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('total_comision', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total_descuento', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total_ingreso', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('pago_total', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('pago_neto', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('activa', models.BooleanField(blank=True, default=False)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empleado.Empleado')),
            ],
            options={
                'db_table': 'boleta_pago',
            },
        ),
        migrations.CreateModel(
            name='CatalogoDescuento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=75)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('descuento_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('cantidad_descontada', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fijo', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'catalogo_descuento',
            },
        ),
        migrations.CreateModel(
            name='CatalogoIngreso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=75)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('ingreso', models.DecimalField(decimal_places=2, max_digits=8)),
                ('comision', models.BooleanField(default=False)),
                ('porcentaje', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
            ],
            options={
                'db_table': 'catalogo_ingreso',
            },
        ),
        migrations.CreateModel(
            name='DescuentoEmpleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('descuento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='planilla.CatalogoDescuento')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empleado.Empleado')),
            ],
            options={
                'db_table': 'descuento_empleado',
            },
        ),
        migrations.CreateModel(
            name='IngresoEmpleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empleado.Empleado')),
                ('ingreso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='planilla.CatalogoIngreso')),
            ],
            options={
                'db_table': 'ingreso_empleado',
            },
        ),
        migrations.CreateModel(
            name='Planilla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.TextField(max_length=20)),
                ('fecha', models.DateField()),
                ('total_pago_empleado', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('total_descuento', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('total_pagar', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('activa', models.BooleanField(blank=True, default=False)),
            ],
            options={
                'db_table': 'planilla',
            },
        ),
        migrations.AddField(
            model_name='ingresoempleado',
            name='planilla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='planilla.Planilla'),
        ),
        migrations.AddField(
            model_name='descuentoempleado',
            name='planilla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='planilla.Planilla'),
        ),
        migrations.AddField(
            model_name='boletapago',
            name='planilla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='planilla.Planilla'),
        ),
    ]
