# Generated by Django 2.1.15 on 2020-06-14 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoDescuento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=75)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fijo', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'catalogo_descuento',
            },
        ),
        migrations.CreateModel(
            name='CatalogoIngreso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=75)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('ingreso', models.DecimalField(decimal_places=2, max_digits=8)),
                ('comision', models.BooleanField(default=False)),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'db_table': 'catalogo_ingreso',
            },
        ),
        migrations.CreateModel(
            name='DescuentoEmpleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('descuento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='planilla.CatalogoDescuento')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empleado.Empleado')),
            ],
            options={
                'db_table': 'descuento_empleado',
            },
        ),
        migrations.CreateModel(
            name='DescuentoGeneral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=75)),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=8)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'descuento_general',
            },
        ),
        migrations.CreateModel(
            name='DetallePlanilla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_laborales', models.IntegerField(default=23)),
                ('dias_trabajados', models.IntegerField(default=23)),
                ('descuento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='planilla.DescuentoEmpleado')),
            ],
            options={
                'db_table': 'detalle_planilla',
            },
        ),
        migrations.CreateModel(
            name='IngresoEmpleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empleado.Empleado')),
                ('ingreso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='planilla.CatalogoIngreso')),
            ],
            options={
                'db_table': 'ingreso_empleado',
            },
        ),
        migrations.CreateModel(
            name='Periodicidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio_periodo', models.IntegerField()),
                ('quincenal', models.BooleanField(default=False)),
                ('mensual', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'periodicidad',
            },
        ),
        migrations.CreateModel(
            name='Planilla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.TextField(max_length=20, unique=True)),
                ('fecha', models.DateField()),
                ('total_pago_empleado', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_descuento', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_pagar', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'db_table': 'planilla',
            },
        ),
        migrations.CreateModel(
            name='SalarioMinimo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'salario_minimo',
            },
        ),
        migrations.AddField(
            model_name='detalleplanilla',
            name='ingreso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='planilla.IngresoEmpleado'),
        ),
        migrations.AddField(
            model_name='detalleplanilla',
            name='planilla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='planilla.Planilla'),
        ),
    ]
