# Generated by Django 2.1.15 on 2020-06-14 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planilla',
            name='codigo',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='planilla',
            name='total_descuento',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='planilla',
            name='total_pagar',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='planilla',
            name='total_pago_empleado',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
