# Generated by Django 2.1.15 on 2020-06-16 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogoingreso',
            name='porcentaje',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
