# Generated by Django 2.1.15 on 2020-06-14 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0002_auto_20200613_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='planilla',
            name='activa',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
