# Generated by Django 3.0.5 on 2020-05-03 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tipo_unidad', '0001_initial'),
        ('departamento_organizacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('departamento_organizacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='departamento_organizacion.DepartamentoOrganizacion')),
                ('dirigido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dirigidos', related_query_name='unidad', to='unidad.Unidad')),
                ('tipo_unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tipo_unidad.TipoUnidad')),
            ],
            options={
                'db_table': 'unidades',
            },
        ),
    ]
