# Generated by Django 3.0.5 on 2020-05-10 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.IntegerField()),
                ('minimo', models.DecimalField(decimal_places=2, max_digits=8)),
                ('maximo', models.DecimalField(decimal_places=2, max_digits=8)),
                ('descripcion', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'comisiones',
            },
        ),
    ]
