# Generated by Django 3.0.5 on 2020-05-03 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='identificacion',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='tipo_empleado',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='tipo_identificacion',
            field=models.CharField(max_length=50),
        ),
    ]
