# Generated by Django 3.0.5 on 2020-05-03 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departamento_organizacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentroCostos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presupuesto', models.FloatField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('remanente', models.FloatField()),
                ('departamento_organizacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='departamento_organizacion.DepartamentoOrganizacion')),
            ],
            options={
                'db_table': 'centro_costos',
            },
        ),
    ]
